# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

# Inserts a blank line between shell prompts
add_newline = false

# Replace the '❯' symbol in the prompt with '➜'
[character] # The name of the module we are configuring is 'character'
success_symbol = '[](bold green)' # The 'success_symbol' segment is being set to '➜' with the color 'bold green'

[status]
disabled = false

[sudo]
disabled = false
symbol = ' '

[shell]
disabled = false

# Disable the package module, hiding it from the prompt completely
[package]
disabled = true

[directory]
truncation_length = 3
truncate_to_repo = true
truncation_symbol = '.../'
home_symbol = ''

[directory.substitutions]
'/usr/local/bin' = '/u/l/bin'
'/usr/bin' = '/u/bin'
'/Repos/Git' = 'repos'
'/repos' = 'repos'

[hostname]
disabled = false
ssh_only = false

[line_break]
disabled = true

[localip]
ssh_only = true
format = '@[$localipv4](bold red) '
disabled = false

# Code/Language-specific plugins
[dotnet]
disabled = false

[cmake]
disabled = false

[python]
disabled = false

[rust]
disabled = false

[lua]
disabled = true

[aws]
disabled = false
format = '[$symbol($profile )(\($region\) )(\[$duration\] )]($style)'
style = 'bold yellow'
region_aliases = { 'us-west-2' = 'uw2' }
force_display = true
